name: Tests
on:
  push:
    paths:
      - "**/*"
      - "!.gitattributes"
      - "!.gitignore"
      - "!README.md"
jobs:
  install:
    name: install-nix-home-manager
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update package
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
      - name: Create nix configuration
        run: |
          sudo mkdir /etc/nix
          echo "build-users-group = " | sudo tee /etc/nix/nix.conf > /dev/null
      - name: Install nix and initialize home manager
        run: |
          sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install) --no-daemon
          sleep 1
          . /home/$USER/.nix-profile/etc/profile.d/nix.sh
          sleep 1
          nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
          nix-channel --add https://github.com/nix-community/nixGL/archive/main.tar.gz nixgl
          nix-channel --update
          sleep 1
          nix-shell '<home-manager>' -A install
          echo ". /home/$USER/.nix-profile/etc/profile.d/nix.sh" | tee -a ~/.bashrc > /dev/null
          sleep 1
          source ~/.bashrc
          nix --version
          home-manager --version
      - name: Verify home.nix file
        run: ls -lh ~/.config/home-manager/home.nix
